blank_issues_enabled: false
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://github.com/kynetic-ai/kynetic-spec/discussions/new/choose
    about: Preferred starting point if you have any questions or suggestions about configuration, features or behavior.
